# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/spi_master/spi_master.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_master || ORIG_REF_NAME==spi_master} -quiet] -quiet

# IP: bd/spi_master/ip/spi_master_processing_system7_0_0/spi_master_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_master_processing_system7_0_0 || ORIG_REF_NAME==spi_master_processing_system7_0_0} -quiet] -quiet

# IP: bd/spi_master/ip/spi_master_ps7_0_axi_periph_0/spi_master_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_master_ps7_0_axi_periph_0 || ORIG_REF_NAME==spi_master_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/spi_master/ip/spi_master_rst_ps7_0_100M_0/spi_master_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_master_rst_ps7_0_100M_0 || ORIG_REF_NAME==spi_master_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/spi_master/ip/spi_master_ila_0_1/spi_master_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_master_ila_0_1 || ORIG_REF_NAME==spi_master_ila_0_1} -quiet] -quiet

# IP: bd/spi_master/ip/spi_master_clk_wiz_0/spi_master_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_master_clk_wiz_0 || ORIG_REF_NAME==spi_master_clk_wiz_0} -quiet] -quiet

# IP: bd/spi_master/ip/spi_master_spi_master_ip_1_0/spi_master_spi_master_ip_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_master_spi_master_ip_1_0 || ORIG_REF_NAME==spi_master_spi_master_ip_1_0} -quiet] -quiet

# IP: bd/spi_master/ip/spi_master_auto_pc_0/spi_master_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_master_auto_pc_0 || ORIG_REF_NAME==spi_master_auto_pc_0} -quiet] -quiet

# XDC: bd/spi_master/spi_master_ooc.xdc
