# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CESE/5B2025/MyS/trabajo_final/Sintesis/spi_master.srcs/sources_1/bd/spi_master/ip/spi_master_ila_0_1/spi_master_ila_0_1.xci
# IP: The module: 'spi_master_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CESE/5B2025/MyS/trabajo_final/Sintesis/spi_master.srcs/sources_1/bd/spi_master/ip/spi_master_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_master_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CESE/5B2025/MyS/trabajo_final/Sintesis/spi_master.srcs/sources_1/bd/spi_master/ip/spi_master_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_master_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CESE/5B2025/MyS/trabajo_final/Sintesis/spi_master.srcs/sources_1/bd/spi_master/ip/spi_master_ila_0_1/spi_master_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_master_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CESE/5B2025/MyS/trabajo_final/Sintesis/spi_master.srcs/sources_1/bd/spi_master/ip/spi_master_ila_0_1/spi_master_ila_0_1.xci
# IP: The module: 'spi_master_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CESE/5B2025/MyS/trabajo_final/Sintesis/spi_master.srcs/sources_1/bd/spi_master/ip/spi_master_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_master_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CESE/5B2025/MyS/trabajo_final/Sintesis/spi_master.srcs/sources_1/bd/spi_master/ip/spi_master_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_master_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CESE/5B2025/MyS/trabajo_final/Sintesis/spi_master.srcs/sources_1/bd/spi_master/ip/spi_master_ila_0_1/spi_master_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_master_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
